### ISSUE TITLE
haskoin-core-0.9.8: No instance for (MonadFail PutM) for ghc-8.8

### ISSUE THREAD

**Issue by juhp** [jprupp/haskoin-core#382]
Fails to build with ghc-8.8.1 (current Stackage Nightly)

```
    Building library for haskoin-core-0.9.8..
    [ 9 of 41] Compiling Network.Haskoin.Script.Common
    
    /var/stackage/work/unpack-dir/unpacked/haskoin-core-0.9.8-3e5e05698092e5a29726fb538220d3ba0e5adbfc827d55de06a2cb09d56a3ab1/src/Network/Haskoin/Script/Common.hs:383:44: error:
        • No instance for (MonadFail PutM) arising from a use of ‘fail’
        • In the second argument of ‘($)’, namely
            ‘fail "OP_PUSHDATA OPCODE: Payload size too big"’
          In a stmt of a 'do' block:
            unless (len <= 0x4b)
              $ fail "OP_PUSHDATA OPCODE: Payload size too big"
          In the expression:
            do unless (len <= 0x4b)
                 $ fail "OP_PUSHDATA OPCODE: Payload size too big"
               putWord8 $ fromIntegral len
        |
    383 |                     unless (len <= 0x4b) $ fail
        |                                            ^^^^...
```

**Comment by jprupp** [comment]
Ah, this one escaped me. It will be fixed for version 0.9.9.

**Comment by juhp** [comment]
Thanks
